src/components/sections/SectionPicker.vue

Correct null check during image name set

Explicitly check if null

---

src/content.ts

Links to https://universal-blue.discourse.group/docs?topic=2291

Change documentation link to the new "landing page"

---

public/image-picker.html

Reverts castrojo/bluefin-website#28

Revert "Update image-picker.html"

---

package-lock.json

This PR upgrades the dependencies of the website and makes it build again. It gets a couple of warnings about SASS Depreciation's but it builds just fine.

fix: fix website not building by upgrading deps

---

public/image-picker.html

This is just for show. The wording needs to be cleaned up and I don't know the actual names of the ISOs that should be selected.
But it's a start!

add GTS selector to image picker

---

README.md
src/App.vue
src/components/scenes/SceneLanding.vue
src/locales/schema.ts
src/main.ts

Should make it a tiny bit easier to make your own translation for this website

refactor: better internationalization support + contributing docs

---

src/App.vue
src/components/scenes/SceneLanding.vue

For some reason CI is a bit stricter than my personal system, this should fix the latest build's error

fix: build errors that CI caught

---

src/components/ImagePicker.vue

- **Update metrics.plugin.pagespeed.svg - [Skip GitHub Action]**
- **Update metrics.plugin.pagespeed.svg - [Skip GitHub Action]**
- **revert: do not add latest to the image picker**

revert: do not have :latest in the picker

---

src/locales/de-DE.json
src/locales/schema.ts

This work supersedes @karhima 's work and builds upon it. Sadly I cannot take his branch and fork it but my branch includes all of their translations and my improvements on top of it.

feat: add german translation to bluefin website

---

src/locales/pt-BR.json

Needed quite a bit of clean-up and reworking, should be a lot more professional now.

chore: Major refactoring for the Brazilian locale

---

README.md
src/App.vue
src/components/FaqItem.vue
src/components/ImagePicker.vue
src/components/Navigation.vue
src/components/common/SceneContent.vue
src/components/scenes/SceneDevelopers.vue
src/components/scenes/SceneLanding.vue
src/components/scenes/SceneUsers.vue
src/components/sections/SectionFooter.vue
src/components/sections/SectionMission.vue
src/components/sections/SectionNews.vue
src/components/sections/SectionPicker.vue
src/components/sections/SectionVideo.vue
src/locales/pt-BR.json
src/locales/schema.ts

This should make translations a bit easier to make since it wont require any modifications to any files, just plop the json file in src/locales and the code will import the file for them. This seems to build fine on Node and BunJS

feat: automatic language file importing

---

src/locales/en-US.json

Im --> I'm and less "!" because i'm no fun!

Better grammar for the website

---

src/components/ImagePicker.vue

Reverts castrojo/bluefin-website#59

Revert "Update ImagePicker.vue"

---

src/components/sections/SectionPicker.vue

Fixes https://github.com/ublue-os/bluefin/issues/2091

fix: set url color on ImagePicker to be the same as the rest of the website

---

src/components/ImagePicker.vue
src/components/sections/SectionPicker.vue

fix: remove blue color from download button

---

src/components/ImagePicker.vue

This does not remove the "GTS Users" notice, though!

chore: disable GTS for now from the picker

---

src/locales/sk-SK.json

When I went to commit this,  I saw a commit changing text in the US locale. I changed it accordingly, but didn't remove the GTS option as it might be used when the ISOs become available again.

Add Slovakian translation 

---

package-lock.json
package.json
postcss.config.js
tailwind.config.js

Upgrade Tailwind CSS and related dependencies

Update Tailwind CSS configuration and dependencies

---

package-lock.json
package.json
postcss.config.js
tailwind.config.js

Reverts castrojo/bluefin-website#101

revert: "Update Tailwind CSS configuration and dependencies"

---

src/content.ts

Reverts castrojo/bluefin-website#108

Revert "Update content.ts"

---

src/components/scenes/SceneLanding.vue
src/content.ts

feat: achillobator at the top of the website :)

---

src/components/scenes/SceneLanding.vue
src/style/overrides/_tablet.scss

fix: make achillobator look good on mobile

---

src/locales/nl-NL.json

This PR adds the Dutch language to the site.

Create nl-NL.json + add Dutch language

---

src/components/ImagePicker.vue
src/locales/de-DE.json
src/locales/en-US.json
src/locales/eo.json
src/locales/ja-JP.json
src/locales/nl-NL.json
src/locales/pt-BR.json
src/locales/ru-RU.json
src/locales/sk-SK.json
src/locales/vi-VN.json
src/style/index.scss

Can be merged whenever LTS has live ISOs and our live ISOs dont have the `-live` suffix.

feat: add ARM and LTS to the picker

---

src/components/Navigation.vue
src/components/scenes/SceneLanding.vue
src/components/sections/SectionPicker.vue

Installer broke everything, we need to not-have an installer for now.

fix: bluefin is unavailable

---

src/components/ImagePicker.vue
src/components/Navigation.vue
src/components/scenes/SceneLanding.vue
src/components/sections/SectionPicker.vue

This just reverts the disabling of the image picker and changes the handling to just be the old ISOs

revert: re-enable image-picker w/ old image handling

---

src/components/ImagePicker.vue

Removes the function that was making the build red

fix: make build green (again)

---

src/components/ImagePicker.vue

Makes the dino slightly smaller on the image picker

fix(image-picker): make dino slightly smaller

---

public/contributors.html

Reverts ublue-os/bluefin-website#267

Revert "Limit "Our Flock" contributors section to 50 entries with top 10 guaranteed"

---

public/contributors.html

Reverts ublue-os/bluefin-website#265

Revert "Enhance Our Flock contributors section with more contributors and GitHub link"

---

src/content.ts

Reverts ublue-os/bluefin-website#323

Revert "Set angry as temporary header image"

---

src/components/ImageChooser.vue
src/components/ImagePicker.vue

Reverts ublue-os/bluefin-website#354

Revert "feat: Darken dinosaur background images in chooser cards for improved text legibility"

---

src/components/ImageChooser.vue
src/style/app/sections/_footer.scss

This will center the text under the "OUR FLOCK" header, increase the size of the "Choose a different release" button and increase the size of the image-chooser badges.

chore: align and resize elements

---

package-lock.json
package.json
src/App.vue
src/components/DocusaurusHeader.vue

Fixes #397
- Added DocusaurusHeader.vue component for navigation with theme toggle and search functionality.
- Integrated Algolia search with DocSearch for documentation search.
- Implemented header opacity change on scroll.
- Updated App.vue to include DocusaurusHeader and manage header opacity state.
- Added styles for the new header and mobile menu.
- Updated package.json to include algoliasearch dependency.

Add Docs Header

---

src/components/ImageChooser.vue

Reverts ublue-os/bluefin-website#417

Revert "Fix LTS ISO chooser workflow: move GPU selection before kernel, skip kernel question for Nvidia users"

---

src/components/ImageChooser.vue

closes #416 
https://github.com/user-attachments/assets/e413bca5-20e2-447a-b4b5-30af08ab1967

feat: enhance image chooser component

---

src/components/ImageChooser.vue

Removed beta flag from the Bluefin lts entry.

Remove beta flag from Bluefin lts entry
